---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
apiVersion: v1
kind: Service
metadata:
 name: nextcloud
 namespace: nextcloud
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nextcloud
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextcloud
  name: nextcloud
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
  replicas: 1
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - image: docker.io/nextcloud:latest
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: username
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database
        - name: POSTGRES_HOST
          value: postgresql
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        name: nextcloud
