---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: nextcloud
stringData:
  password: CHANGEME
  username: CHANGEME
  database: CHANGEME
---
apiVersion: v1
kind: Service
metadata:
 name: postgresql
 namespace: nextcloud
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: postgresql
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: username
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database
        image: docker.io/postgres:14-alpine
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5432
          protocol: TCP
        name: postgresql
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: pgdata
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: postgresql
